### ISSUE TITLE
Extension does not activate

### ISSUE THREAD

**Issue by PurpleMagick** [berkansivri/VsCode-njsproj#6]
Synopsis: I've installed the extension and it fails to activate. Looking at the Extension Host log, I get the following 

```
[2020-10-14 09:14:41.107] [exthost] [error] Activating extension berkansivri.vscode-njsproj failed due to an error:
[2020-10-14 09:14:41.108] [exthost] [error] Error: Cannot find module '[my user directory]\.vscode\extensions\berkansivri.vscode-njsproj-0.6.1\src\extension.js'
Require stack:
- [my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- [my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- [my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
	at Module._load (internal/modules/cjs/loader.js:737:27)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1057:776)
	at Function.i._load ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1027:486)
	at Function.n._load ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1023:767)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:34:963)
	at p._loadCommonJSModule ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1028:771)
	at p._doActivateExtension ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:742)
	at p._activateExtension ([my user directory]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:924:822)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 6)
	at async Promise.all (index 0)
```

The problem seems to be that it's trying to load the file from the **src** directory but the extension only ships with the **dist** directory.

I modified **.vscode\extensions\berkansivri.vscode-njsproj-0.6.1\package.json** and changed the line

```
"main": "./src/extension.js"
```

to

```
"main": "./dist/extension.js"
```

Then after opening VSCode again I got a popup saying the extension was modified and prompting me to reload. After doing that, the extension successfully loaded and worked.

I'm not sure if this is the only change needed in the source code, otherwise I would have directly made a PR. I'll investigate more and perhaps make one at a later date if it hasn't been fixed yet.

**Comment by berkansivri** [comment]
I am sorry for being late. I just published a new version according to your issue and advice. Please let me new if you find any other issue related to vscode updates. Thank you.
